name: CannonCore
main: dalabi.cannon.Main
author: DaLabi
version: 1.0.0
description: should work
commands:
  cannoncore:
    description: main plugin command.
  ms:
    description: gives magicsand.
    aliases: [magicsand,sand,sandbot,magic]
  refill:
    description: refills nearby magicsand.
  fire:
    description: fires a button.
  lever:
    description: flicks a lever.
  tickcounter:
    description: counts ticks on repeaters.
    aliases: [tc]
  buildhelper:
    description: toggles build helper mode.
    aliases: [bh]
    